development:
  bucket: bookcamping
  access_key_id: AKIAJEYGNZI3ZGKEZ5LQ
  secret_access_key: 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

test:
  bucket: bookcamping-test
  access_key_id: AKIAJEYGNZI3ZGKEZ5LQ
  secret_access_key: 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


production:
  bucket: bookcamping
  access_key_id: AKIAJEYGNZI3ZGKEZ5LQ
  secret_access_key: 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

